/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddImage: typeof import('./src/components/modules/add_image/AddImage.vue')['default']
    BtnDelete: typeof import('./src/components/form/BtnDelete.vue')['default']
    BtnMini: typeof import('./src/components/form/BtnMini.vue')['default']
    BtnStandart: typeof import('./src/components/form/BtnStandart.vue')['default']
    BtnThreeDotsVertical: typeof import('./src/components/form/BtnThreeDotsVertical.vue')['default']
    BtnToggleShowFace: typeof import('./src/components/form/BtnToggleShowFace.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    CategoryForm: typeof import('./src/components/modules/CategoryForm.vue')['default']
    CategoryItem: typeof import('./src/components/CategoryItem.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterDateCreate: typeof import('./src/components/modules/add_image/FilterDateCreate.vue')['default']
    FilterTag: typeof import('./src/components/modules/add_image/FilterTag.vue')['default']
    FilterTagItem: typeof import('./src/components/modules/add_image/FilterTagItem.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageItem: typeof import('./src/components/tag/ImageItem.vue')['default']
    ImageItemControlBlock: typeof import('./src/components/image_list_item/ImageItemControlBlock.vue')['default']
    ImageItemCreateDate: typeof import('./src/components/image_list_item/ImageItemCreateDate.vue')['default']
    ImageItemDeleteConfirm: typeof import('./src/components/image_list_item/ImageItemDeleteConfirm.vue')['default']
    ImageItemTagsControl: typeof import('./src/components/modules/ImageItemTagsControl.vue')['default']
    ImagesListItem: typeof import('./src/components/image_list_item/ImagesListItem.vue')['default']
    InputForm: typeof import('./src/components/form/InputForm.vue')['default']
    InputTextarea: typeof import('./src/components/form/InputTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TagItem: typeof import('./src/components/modules/tags_control/TagItem.vue')['default']
    TagsControl: typeof import('./src/components/modules/tags_control/TagsControl.vue')['default']
    UploadImage: typeof import('./src/components/form/UploadImage.vue')['default']
    UpScrollPage: typeof import('./src/components/UpScrollPage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
